- name: apache installation
  when: ansible_distribution_version  == "7.8"
  yum:
    name: httpd
    state: latest
  
- name: Start apache
  when: ansible_distribution_version  == "7.8"
  systemd:
    name: httpd
    state: started