---
  - name: creating empty file
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars_files:
      - "../variables/values-variables.yaml"
    tasks:
      - name: creating empty file 
        file:
          state: "{{ state }}"
          path: /tmp/"{{ path }}"
          mode: "{{ mode }}"
