---
  - name: copy index.html file into application server
    hosts: development
    tasks:
      - name: copy index.html file into application server
        when: ansible_hostname == "application"
        copy:
          src: /tmp/index.html
          dest: /var/www/html/
          owner: apache
          group: apache
          