---
  - name: This is ping playbook
    hosts: development
    gather_facts: no
    tasks: 
      - name: Ping hosts
        ping: 
      
      - name: Run 'ls' command
        command: "{{ item }}"
        with_items:
          - ls
          - pwd
        register: command_output
    
      - name: run 'debug' to read command output
        debug: 
          var: command_output
      