---
  - name: check free disk in managed servers
    hosts: "{{ group }}"
    tasks: 
      - name: 
        when: ansible_distribution=="CentOS" and ansible_distribution_major_version=="7"
        command: df -h 
        register: df_check
      
      - debug: var=df_check