---
  - name: wordpress
    gather_facts: "{{ gather_facts }}"
    hosts: "{{ group }}"
    vars_files: 
      - '../variables/variables'
    tasks:    
      
      - name:
        copy:
          remote_src: true
          src: /var/www/html/wp-config-sample.php
          dest: /var/www/html/wp-config.php
        
      - name: create upload directory inwordpress wp-content
        file:
          path: /var/www/html/wp-content/uploads
          state: directory
          mode: '660'
      
      - name: Give ownership to an existing file
        file:
          path: /var/www/html/wp-config.php
          owner: apache
          group: apache
      
      - name: install MySQL-python
        yum:
          name: MySQL-python
          state: latest

      - name: Create a new database 'wordpress'
        mysql_db:
          name: wordpress
          state: present

      - name: Removes all anonymous user accounts
        mysql_user:
          name: ''
          host_all: yes
          state: absent
      
      - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
        mysql_user:
          name: wordpressuser
          password: redhat
          priv: '*.*:ALL,GRANT'
          state: present